services:
  flask-app:
    container_name: flask-app
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
